<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableHarmony>true</EnableHarmony>
    <AssemblyName>Cardcha</AssemblyName>
    <RootNamespace>Cardcha</RootNamespace>
    <Version>0.3.0-alpha.28.0.4.14.4.5.12.4</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets/**" CopyToOutputDirectory="PreserveNewest" />
    <None Update="i18n/**" CopyToOutputDirectory="PreserveNewest" />
    <None Update="manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
