<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableHarmony>true</EnableHarmony>
    <AssemblyName>Cardcha</AssemblyName>
    <RootNamespace>Cardcha</RootNamespace>
    <Version>0.1.17-alpha.11.36</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets/**" CopyToOutputDirectory="PreserveNewest" />
    <None Update="i18n/**" CopyToOutputDirectory="PreserveNewest" />
    <None Update="manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
